#!/usr/bin/env bash

set -euo pipefail


if [ -z "$1" ]; then
    echo "provide vpc id"
else
    export VPC_ID="$1"
fi

if [ -z "$3" ]; then
    echo "provide IGW id"
else
    export IGW_ID="$3"
fi

if [ -z "$2" ]; then
    echo "provide AST id"
else
    export AST_ID="$2"
fi

if [ -z "$4" ]; then
    echo "provide subnet id"
else
    export SUBNET_ID="$4"
fi

if [ -z "$5" ]; then
    echo "provide RT id"
else
    export RT_ID="$5"
fi


# detach the IGW
aws ec2 detach-internet-gateway --internet-gateway-id $IGW_ID --vpc-id $VPC_ID

# delete the IGW
aws ec2 delete-internet-gateway --internet-gateway-id $IGW_ID

# dissacociate subnet
aws ec2 disassociate-route-table --association-id $AST_ID

# delete subnet
aws ec2 delete-subnet --subnet-id $SUBNET_ID

# delete the route table
# aws ec2 delete-route-table --route-table-id $RT_ID

# delete vpc
aws ec2 delete-vpc --vpc-id $VPC_ID
