#!/usr/bin/env bash

echo "== delete objects =="

# getting the bucket name from cli
if [ -z "$1" ]; then
    echo "There needs to be a bucket name  e.g. ./bucket my-bucket-name"
    exit 1
fi


BUCKET_NAME=$1

# {
#     "Objects": [
#         {
#             "key": "test1.txt"
#         }
#     ],
#     "Quiet": false
# }



aws s3api list-objects-v2 \
--bucket $BUCKET_NAME \
--query Contents[].Key \
| jq -n '{Objects: [inputs | .[] | {Key: .}]}' > /tmp/delete_objects.json

aws s3api delete-objects --bucket $BUCKET_NAME --delete file:///tmp/delete_objects.json


