#!/usr/bin/env bash

echo "== put object =="

# getting the bucket name from cli
if [ -z "$1" ]; then
    echo "There needs to be a bucket name  e.g. ./bucket my-bucket-name"
    exit 1
fi

# getting the file name from cli
if [ -z "$2" ]; then
    echo "There needs to be a file name e.g. ./bucket my-bucket-name filename"
    exit 1
fi

BUCKET_NAME=$1
FILENAME=$2

# used to extract the basename, which is the filename
# extracted from the absolute path of the given path
OBJECT_KEY=$(basename "$FILENAME")

aws s3api put-object \
--bucket $BUCKET_NAME \
--body $FILENAME \
--key $OBJECT_KEY
