#!/usr/bin/env bash

echo "== sync =="

# this command will make the bash script stop immediately when an error is encountered
set -e


# getting the bucket name from cli
if [ -z "$1" ]; then
    echo "There needs to be a bucket name e.g. ./bucket my-bucket-name"
    exit 1
fi

# getting the file name prefix from cli
if [ -z "$2" ]; then
    echo "There needs to be a file name prefix e.g. ./bucket my-bucket-name filename-prefix"
    exit 1
fi

BUCKET_NAME=$1
FILENAME_PREFIX=$2

# where we'll store these objects
OUTPUT_DIR="/tmp/s3-bash-scripts"

# remove the folder/files if some junk files are present
rm -rf $OUTPUT_DIR

# creating output folder
mkdir -p $OUTPUT_DIR

# generate a random number
# to determine how many files to create
NUM_FILES=$((RANDOM % 6 + 5))

# create random files
for ((i=1; i <= NUM_FILES; i++)); do
    # random file name
    FILENAME="$OUTPUT_DIR/${FILENAME_PREFIX}_$i.txt"

    # generate random data and write it to the file
    dd if=/dev/urandom of="$FILENAME" bs=1024 count=$((RANDOM % 1024 + 1)) 2>/dev/null
done

tree $OUTPUT_DIR

echo "== files created, now syncing =="

aws s3 sync $OUTPUT_DIR s3://$BUCKET_NAME 