#!/usr/bin/env bash

echo "== deploying s3 bucket using cfn =="

# create-stack and delete-stack are older versions and both of them are consolodated into `deploy` in newer versions

STACK_NAME="cfn-s3-simple"

aws cloudformation deploy \
--template-file template.yaml \
--region ap-south-1 \
--stack-name $STACK_NAME \
--no-execute-changeset

# what is changeset?